export const resources = [
  {
    name: "Amenity",
    list: "/amenity",
    show: "/amenity/show/:id",
    edit: "/amenity/edit/:id",
    create: "/amenity/create",
    meta: { label: "Amenity" },
  },
  {
    name: "BookingTimeSlot",
    list: "/BookingTimeSlot",
    show: "/BookingTimeSlot/show/:id",
    edit: "/BookingTimeSlot/edit/:id",
    create: "/BookingTimeSlot/create",
    meta: { label: "BookingTimeSlot" },
  },
  {
    name: "Business",
    list: "/Business",
    show: "/Business/show/:id",
    edit: "/Business/edit/:id",
    create: "/Business/create",
    meta: { label: "Business" },
  },
  {
    name: "BusinessBooking",
    list: "/BusinessBooking",
    show: "/BusinessBooking/show/:id",
    edit: "/BusinessBooking/edit/:id",
    create: "/BusinessBooking/create",
    meta: { label: "BusinessBooking" },
  },
  {
    name: "BusinessBoost",
    list: "/BusinessBoost",
    show: "/BusinessBoost/show/:id",
    edit: "/BusinessBoost/edit/:id",
    create: "/BusinessBoost/create",
    meta: { label: "BusinessBoost" },
  },
  {
    name: "BusinessCategory",
    list: "/BusinessCategory",
    show: "/BusinessCategory/show/:id",
    edit: "/BusinessCategory/edit/:id",
    create: "/BusinessCategory/create",
    meta: { label: "BusinessCategory" },
  },
  {
    name: "BusinessDeal",
    list: "/BusinessDeal",
    show: "/BusinessDeal/show/:id",
    edit: "/BusinessDeal/edit/:id",
    create: "/BusinessDeal/create",
    meta: { label: "BusinessDeal" },
  },
  {
    name: "BusinessFollowing",
    list: "/BusinessFollowing",
    show: "/BusinessFollowing/show/:id",
    edit: "/BusinessFollowing/edit/:id",
    create: "/BusinessFollowing/create",
    meta: { label: "BusinessFollowing" },
  },
  {
    name: "BusinessHour",
    list: "/BusinessHour",
    show: "/BusinessHour/show/:id",
    edit: "/BusinessHour/edit/:id",
    create: "/BusinessHour/create",
    meta: { label: "BusinessHour" },
  },
  {
    name: "BusinessLocation",
    list: "/BusinessLocation",
    show: "/BusinessLocation/show/:id",
    edit: "/BusinessLocation/edit/:id",
    create: "/BusinessLocation/create",
    meta: { label: "BusinessLocation" },
  },
  {
    name: "BusinessProduct",
    list: "/BusinessProduct",
    show: "/BusinessProduct/show/:id",
    edit: "/BusinessProduct/edit/:id",
    create: "/BusinessProduct/create",
    meta: { label: "BusinessProduct" },
  },
  {
    name: "BusinessProductPrice",
    list: "/BusinessProductPrice",
    show: "/BusinessProductPrice/show/:id",
    edit: "/BusinessProductPrice/edit/:id",
    create: "/BusinessProductPrice/create",
    meta: { label: "BProductPrice" },
  },
  {
    name: "BusinessTag",
    list: "/BusinessTag",
    show: "/BusinessTag/show/:id",
    edit: "/BusinessTag/edit/:id",
    create: "/BusinessTag/create",
    meta: { label: "BusinessTag" },
  },
  {
    name: "BusinessUpdate",
    list: "/BusinessUpdate",
    show: "/BusinessUpdate/show/:id",
    edit: "/BusinessUpdate/edit/:id",
    create: "/BusinessUpdate/create",
    meta: { label: "BusinessUpdate" },
  },
  {
    name: "City",
    list: "/City",
    show: "/City/show/:id",
    edit: "/City/edit/:id",
    create: "/City/create",
    meta: { label: "City" },
  },
  {
    name: "Country",
    list: "/Country",
    show: "/Country/show/:id",
    edit: "/Country/edit/:id",
    create: "/Country/create",
    meta: { label: "Country" },
  },
  {
    name: "Currency",
    list: "/Currency",
    show: "/Currency/show/:id",
    edit: "/Currency/edit/:id",
    create: "/Currency/create",
    meta: { label: "Currency" },
  },
  {
    name: "DealsRedemption",
    list: "/DealsRedemption",
    show: "/DealsRedemption/show/:id",
    edit: "/DealsRedemption/edit/:id",
    create: "/DealsRedemption/create",
    meta: { label: "DealsRedemption" },
  },
  {
    name: "Event",
    list: "/Event",
    show: "/Event/show/:id",
    edit: "/Event/edit/:id",
    create: "/Event/create",
    meta: { label: "Event" },
  },
  {
    name: "EventCategory",
    list: "/EventCategory",
    show: "/EventCategory/show/:id",
    edit: "/EventCategory/edit/:id",
    create: "/EventCategory/create",
    meta: { label: "EventCategory" },
  },
  {
    name: "Language",
    list: "/Language",
    show: "/Language/show/:id",
    edit: "/Language/edit/:id",
    create: "/Language/create",
    meta: { label: "Language" },
  },
  {
    name: "Media",
    list: "/Media",
    show: "/Media/show/:id",
    edit: "/Media/edit/:id",
    create: "/Media/create",
    meta: { label: "Media" },
  },
  {
    name: "Payment",
    list: "/Payment",
    show: "/Payment/show/:id",
    edit: "/Payment/edit/:id",
    create: "/Payment/create",
    meta: { label: "Payment" },
  },
  {
    name: "PaymentMethod",
    list: "/PaymentMethod",
    show: "/PaymentMethod/show/:id",
    edit: "/PaymentMethod/edit/:id",
    create: "/PaymentMethod/create",
    meta: { label: "PaymentMethod" },
  },
  {
    name: "PaymentCategory",
    list: "/PaymentCategory",
    show: "/PaymentCategory/show/:id",
    edit: "/PaymentCategory/edit/:id",
    create: "/PaymentCategory/create",
    meta: { label: "PaymentCategory" },
  },
  {
    name: "Province",
    list: "/Province",
    show: "/Province/show/:id",
    edit: "/Province/edit/:id",
    create: "/Province/create",
    meta: { label: "Province" },
  },
  {
    name: "Region",
    list: "/Region",
    show: "/Region/show/:id",
    edit: "/Region/edit/:id",
    create: "/Region/create",
    meta: { label: "Region" },
  },
  {
    name: "Report",
    list: "/Report",
    show: "/Report/show/:id",
    edit: "/Report/edit/:id",
    create: "/Report/create",
    meta: { label: "Report" },
  },
  {
    name: "Transaction",
    list: "/Transaction",
    show: "/Transaction/show/:id",
    edit: "/Transaction/edit/:id",
    create: "/Transaction/create",
    meta: { label: "Transaction" },
  },
  {
    name: "User",
    list: "/User",
    show: "/User/show/:id",
    edit: "/User/edit/:id",
    create: "/User/create",
    meta: { label: "User" },
  },
  {
    name: "UserAction",
    list: "/UserAction",
    show: "/UserAction/show/:id",
    edit: "/UserAction/edit/:id",
    create: "/UserAction/create",
    meta: { label: "UserAction" },
  },
  {
    name: "UserActionLog",
    list: "/UserActionLog",
    show: "/UserActionLog/show/:id",
    edit: "/UserActionLog/edit/:id",
    create: "/UserActionLog/create",
    meta: { label: "UserActionLog" },
  },
  {
    name: "UserBlocked",
    list: "/UserBlocked",
    show: "/UserBlocked/show/:id",
    edit: "/UserBlocked/edit/:id",
    create: "/UserBlocked/create",
    meta: { label: "UserBlocked" },
  },
  {
    name: "UserBooking",
    list: "/UserBooking",
    show: "/UserBooking/show/:id",
    edit: "/UserBooking/edit/:id",
    create: "/UserBooking/create",
    meta: { label: "UserBooking" },
  },
  {
    name: "UserBookmark",
    list: "/UserBookmark",
    show: "/UserBookmark/show/:id",
    edit: "/UserBookmark/edit/:id",
    create: "/UserBookmark/create",
    meta: { label: "UserBookmark" },
  },
  {
    name: "UserCheckin",
    list: "/UserCheckin",
    show: "/UserCheckin/show/:id",
    edit: "/UserCheckin/edit/:id",
    create: "/UserCheckin/create",
    meta: { label: "UserCheckin" },
  },
  {
    name: "UserFollowing",
    list: "/UserFollowing",
    show: "/UserFollowing/show/:id",
    edit: "/UserFollowing/edit/:id",
    create: "/UserFollowing/create",
    meta: { label: "UserFollowing" },
  },
  {
    name: "UserPreference",
    list: "/UserPreference",
    show: "/UserPreference/show/:id",
    edit: "/UserPreference/edit/:id",
    create: "/UserPreference/create",
    meta: { label: "UserPreference" },
  },
  {
    name: "UserReview",
    list: "/UserReview",
    show: "/UserReview/show/:id",
    edit: "/UserReview/edit/:id",
    create: "/UserReview/create",
    meta: { label: "UserReview" },
  },
  {
    name: "UserScore",
    list: "/UserScore",
    show: "/UserScore/show/:id",
    edit: "/UserScore/edit/:id",
    create: "/UserScore/create",
    meta: { label: "UserScore" },
  },
  {
    name: "UserVerification",
    list: "/UserVerification",
    show: "/UserVerification/show/:id",
    edit: "/UserVerification/edit/:id",
    create: "/UserVerification/create",
    meta: { label: "UserVerification" },
  },
  {
    name: "UserWallet",
    list: "/UserWallet",
    show: "/UserWallet/show/:id",
    edit: "/UserWallet/edit/:id",
    create: "/UserWallet/create",
    meta: { label: "UserWallet" },
  },
];
